### ISSUE TITLE
Use TRESOR in-VM to protect against attacks on vRAM  

### ISSUE THREAD

**Issue by tabbyrobin** [rustybird/qubes-split-dm-crypt#2]
From the readme:
> After detaching, the password and/or key will linger in more RAM locations than without Split dm-crypt. Until there is a way to wipe the DisposableVMs' memory, and qvm-block-split is modified not to pass the key through dom0's memory, power off your computer when memory forensics is a concern.

Could using Tresor help to mitigate this kind of attack? There are limits to Tresor's usefulness in virtualized environments but it seems like it would still bring some benefit:

> Cold boot attacks on the CPU: - on real processors registers are cleared to zero on both hardware resets and software resets ("Ctrl-Alt-Delete"). However CPU registers are currently vulnerable on virtual machines, since they are reset during simulated hardware resets but not during software resets. The authors deem this an apparent flaw in many implementations of virtual machines, but note that virtual systems would be inherently vulnerable even if this were rectified, since all registers on a virtual machine are likely to be accessible using the host system. https://en.wikipedia.org/wiki/TRESOR

**Comment by rustybird** [comment]
It wouldn't really help, unfortunately. The additional RAM copies happen because

1. _Split dm-crypt_ uses shell scripts to [send the key](https://github.com/rustybird/qubes-split-dm-crypt/blob/89b23d4e34ebd8fed72a321e7453d3ec0f42b65b/vm/etc/qubes-rpc/splitDmCrypt.SendKey%2Bluks1) (from the header DisposableVM) and [receive it](https://github.com/rustybird/qubes-split-dm-crypt/blob/89b23d4e34ebd8fed72a321e7453d3ec0f42b65b/vm/etc/qubes-rpc/splitDmCrypt.Map) (in the device DisposableVM). Those qrexec services could be rewritten in C, Rust, or something else with manual memory allocation, but ...

2. ... I think there's also some buffering going on in the qrexec data connection itself, which could leave copies of the key lying around. :\

3. On its way from the header DisposableVM to the device DisposableVM, the key [passes through dom0's memory](https://github.com/rustybird/qubes-split-dm-crypt/blob/89b23d4e34ebd8fed72a321e7453d3ec0f42b65b/dom0/bin/qvm-block-split#L167-L168). It might be possible to avoid this on R4.0, now that QubesOS/qubes-issues#2181 has been fixed.
